// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smvycuettppgynhfvukm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtdnljdWV0dHBwZ3luaGZ2dWttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MzkwMTAsImV4cCI6MjA2MTMxNTAxMH0.dpGsqbVzsh7vduUAtsBGl8MGX_xLT-BtHFC_LWJ6tww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);